FootballClubsManager/Models/FootballClub.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FootballClubsManager.Models
{
    public class FootballClub
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public List<Player> Players = new();
    }
}

FootballClubsManager/Models/Player.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FootballClubsManager.Models
{
    public class Player
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Age { get; set; }
        public string Country { get; set; }
        public string ClubName { get; set; }
    }
}

FootballClubsManager/Controllers/FootballClubsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FootballClubsManager.Infrastructure;
using FootballClubsManager.Infrastructure.Context;
using FootballClubsManager.Infrastructure.Repositories;
using FootballClubsManager.Services;
using FootballClubsManager.Models;

namespace FootballClubsManager.Controllers
{
    public class FootballClubsController : Controller
    {
        private readonly IFootballClubsService _footballClubService;

        public FootballClubsController(IFootballClubsService footballClubService)
        {
            this._footballClubService = footballClubService;
        }

        // GET: FootballClubControllercs
        public ActionResult Index()
        {
            return View(_footballClubService.GetClubs());
        }

        // GET: FootballClubControllercs/Details/5
        public ActionResult Details()
        {
            return Ok(_footballClubService.GetClubs());
        }

        // GET: FootballClubControllercs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FootballClubControllercs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([FromForm] FootballClub club)
        {
            try
            {
                _footballClubService.InsertClub(club);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FootballClubControllercs/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: FootballClubControllercs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FootballClubControllercs/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FootballClubControllercs/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

FootballClubsManager/Views/FootballClubs/Create.cshtml
@model FootballClubsManager.Models.FootballClub

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>FootballClub</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FootballClubsManager/Views/FootballClubs/Index.cshtml
@model IEnumerable<FootballClubsManager.Models.FootballClub>

@{
    ViewData["Title"] = "Index";
}


<h1>Main Page : @System.Net.Dns.GetHostEntry(System.Net.Dns.GetHostName()).AddressList[0].ToString()</h1>  

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Country</th>
            <th>Players</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (FootballClub club in Model) {
        <tr>
            <td>@club.Name</td>
            <td>@club.Country</td>
            <td>
                @foreach (Player player in club.Players)
                {
                    <ul>@player.Name @player.Surname</ul>
                }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

FootballClubsManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FootballClubsManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="FootballClubs" asp-action="Index">FootballClubsManager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FootballClubs" asp-action="Index">Football clubs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="Index">Players</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FootballClubsManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>